{{- $releaseName := .Release.Name -}}
{{- $chartName := include "osmdbt-wrapper.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}-secret
    environment: {{ include "osmdbt-wrapper.environment" . }}
    release: {{ $releaseName }}
    {{- include "osmdbt-wrapper.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.dbConfig }}
  DB_USERNAME: {{ .username | b64enc }}
  {{- if not .sslAuth.enabled }}
  DB_PASSWORD: {{ .password | b64enc }}
  {{- end }}
  {{- end -}}
  {{- with .Values.objectStrorageConfig }}
  AWS_ACCESS_KEY_ID: {{ .accessKey | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .secretKey | b64enc | quote }}
  {{- end -}}
{{- end }}
